name: Renew ephemeral self-hosted runner token

on: [push, pull_request]
# on:
#   schedule:
#     - cron: '0/30 * * * *'  # "every 30 minutes
jobs:  

  renew_gh-runner_token_for_nano-node:
    #On the work-server the base-container for ther gh-runner is called 'gh-runner-nano-node'
    #A registration token is generated for the repo 'gr0vity-dev/nano-node'
    #The following repo secrets need to be defined : 
    # - secrets.GH_PAT (your personal access token)
    # - secrets.GH_RUNNER_HOST (work server ip address)
    # - secrets.GH_RUNNER_USER (work-server user)
    # - secrets.GH_RUNNER_PRV_KEY (private key to ssh into the workserver)

    name: renew reg token for nano-node
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - name: Use the token in subsequent steps
        id: get_token
        run: |          
          GH_RUNNER_TOKEN=$(curl \
          --location --request POST 'https://api.github.com/repos/gr0vity-dev/nano-node/actions/runners/registration-token' \
          --header 'Authorization: Bearer ${{ secrets.GH_PAT }}' \
          | jq -r '.token')
          echo "::add-mask::$GH_RUNNER_TOKEN"
          echo "{GH_RUNNER_TOKEN}=$GH_RUNNER_TOKEN" >> $GITHUB_STATE

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.GH_RUNNER_HOST }}
          username: ${{ secrets.GH_RUNNER_USER }}
          key: ${{ secrets.GH_RUNNER_PRV_KEY }}
          script: ./git/lxd-github-actions/renew_runner_token gh-runner-nano-node https://github.com/gr0vity-dev/nano-node ${{ steps.get_token.outputs.GH_RUNNER_TOKEN }}
  
  renew_gh-runner_token_for_nano-speed-testsuite:
    #On the work-server the base-container for ther gh-runner is called 'gh-runner-nano-speed-testsuite'
    #A registration token is generated for the repo 'gr0vity-dev/nano-speed-testsuite'
    #The repo secrets are the same as in the job above

    name: renew reg token for nano-speed-testsuite
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - name: Use the token in subsequent steps
        id: get_token
        run: | 
          GH_RUNNER_TOKEN=$(curl \
          --location --request POST 'https://api.github.com/repos/gr0vity-dev/nano-speed-testsuite/actions/runners/registration-token' \
          --header 'Authorization: Bearer ${{ secrets.GH_PAT }}' \
          | jq -r '.token')
          echo "::add-mask::$GH_RUNNER_TOKEN"          
          echo "{GH_RUNNER_TOKEN}=$GH_RUNNER_TOKEN}" >> $GITHUB_STATE

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.GH_RUNNER_HOST }}
          username: ${{ secrets.GH_RUNNER_USER }}
          key: ${{ secrets.GH_RUNNER_PRV_KEY }}
          script: ./git/lxd-github-actions/renew_runner_token gh-runner-nano-speed-testsuite https://github.com/gr0vity-dev/nano-speed-testsuite ${{ steps.get_token.outputs.GH_RUNNER_TOKEN }}