name: Renew ephemeral self-hosted runner token

on: [push, pull_request]
# on:  
#   schedule:
#     - cron: '0/30 * * * *'  # "every 30 minutes
jobs:

  new_token:
    name: renew token
    timeout-minutes: 2 
    runs-on: ubuntu-latest
    steps:
      - name: Get token for self-hosted runner registration
      - uses: roncsak/getRunnerToken@v1.0.2
        uses: ./
        id  : runnerRegistration
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # scope: "organization"

      - name: Use the token in subsequent steps
        run : |          
          echo "Your token expires at: ${{ steps.runnerRegistration.outputs.expires_at }}"